name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote-dir: /home/u199268921/public_html/laravel 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/manish/**

    # - name: Set up PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.0'
    #     extensions: mbstring, zip, pdo, xml, curl, json, openssl

    # - name: Install Composer Dependencies
    #   run: composer install --no-interaction --prefer-dist

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_UNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }} 
        script: |
                whoami
                cd /home/u199268921/public_html/laravel
                composer2 install --no-interaction --no-ansi --no-progress --optimize-autoloader
                php artisan migrate --database=mysql --path=database/migrations/mysql
                php artisan migrate --database=mysql2 --path=database/migrations/mysql2
                php artisan optimize:clear  

    # - name: Deploy to Server 
    #   run: |
    #     ssh -i ${{ secrets.DEPLOY_KEY }} ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_IP }} 'cd /home/u199268921/public_html/laravel  && composer update && composer install --no-interaction --no-ansi --no-progress --optimize-autoloader'
    # - name: Set up Environment
    #   run: cp .env.example .env

    # - name: Generate Application Key
    #   run: php artisan key:generate

    # - name: Configure Database (mysql)
    #   run: |
    #     sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
    #     sed -i 's/DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/' .env
    #     sed -i 's/DB_PORT=.*/DB_PORT=${{ secrets.DB_PORT }}/' .env
    #     sed -i 's/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/' .env
    #     sed -i 's/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/' .env
    #     sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env

    # - name: Migrate Database (mysql)
    #   run: php artisan migrate --database=mysql --force

    # - name: Configure Database (mysql2)
    #   run: |
    #     sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql2/' .env
    #     sed -i 's/DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST_2 }}/' .env
    #     sed -i 's/DB_PORT=.*/DB_PORT=${{ secrets.DB_PORT_2 }}/' .env
    #     sed -i 's/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE_2 }}/' .env
    #     sed -i 's/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME_2 }}/' .env
    #     sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD_2 }}/' .env

    # - name: Migrate Database (mysql2)
    #   run: php artisan migrate --database=mysql2 --force
